---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "azure-voting-app-redis.name" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
  namespace: {{ template "azure-voting-app-redis.name" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      containers:
      - name: azure-vote-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
  namespace: {{ template "azure-voting-app-redis.name" . }}
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back

